### ISSUE TITLE
Show outer rings to indicate what the min and max level for each element is so user can get rhythm in the sweet spot

### ISSUE THREAD

**Issue by chriskwan** [dggriffin/Rain-Rain-Ritual#13]

**Comment by jeffdougherty** [comment]
Does max in this case mean what it should be to make the spell go off correctly?

**Comment by chriskwan** [comment]
Actually, it should be two glowing rings to indicate the minimum and maximum. So the user would want to get between the min and max (and it would be possible to go beyond max too).

**Comment by jeffdougherty** [comment]
Outstanding.  I was going to open a case for exactly that kind of UI element, glad you're ahead of me.  Having the element fade in just isn't enough of a cue, unfortunately.

-JTD

**Comment by chriskwan** [comment]
Fixed by #23
